#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color "#7aa2f7"
bspc config focused_border_color "#7aa2f7"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# compositor
picom -b &

# wallpaper
feh --bg-fill ~/.dotfiles/kali-lincox-wallpapers/lincox6.png &

# bar
$HOME/.config/polybar/launch.sh &
